# Numpy

In [18]:
import csv
import numpy as np
with open('C:/Users/Gautham/Downloads/wineQualityReds.csv','r') as f:
    wines = list(csv.reader(f,delimiter=";"))
    print(wines[:3])

[[',"fixed.acidity","volatile.acidity","citric.acid","residual.sugar","chlorides","free.sulfur.dioxide","total.sulfur.dioxide","density","pH","sulphates","alcohol","quality"'], ['1,7.4,0.7,0,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5'], ['2,7.8,0.88,0,2.6,0.098,25,67,0.9968,3.2,0.68,9.8,5']]


In [ ]:
qualities = [float(item[-1]) for item in wines[1:]]
sum(qualities)/len(qualities)

In [20]:
empty_array = np.zeros((3,4))
empty_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.random.rand(3,4)

array([[0.35287961, 0.9643651 , 0.23585662, 0.58028653],
       [0.55228788, 0.0606873 , 0.24698878, 0.696592  ],
       [0.21909676, 0.99314596, 0.29447067, 0.29542226]])

In [22]:
wines = np.genfromtxt("C:/Users/Gautham/Downloads/wineQualityReds.csv", delimiter=";", skip_header=1)

In [29]:
wines = np.array(wines[1:], dtype=np.float)
wines

array([nan, nan, nan, ..., nan, nan, nan])

In [31]:
wines.astype(int)
wines.dtype.name

'float64'